//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.06 at 05:46:53 PM EET 
//


package db.pcci.ita.msa.cards.soap.client;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for IssuePrimaryCardResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IssuePrimaryCardResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CardOrderManagementResponseHeader" type="{http://www.equens.com/cards/issuing/messages/}CardOrderManagementResponseHeader"/&gt;
 *         &lt;element name="ProductKey"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="IssuerKeyType" type="{http://www.equens.com/cards/issuing/types/v1.0}Max6Text"/&gt;
 *                   &lt;element name="ProductKey" type="{http://www.equens.com/cards/issuing/types/v1.0}Max50Text"/&gt;
 *                   &lt;element name="IssuerKey" type="{http://www.equens.com/cards/issuing/types/v1.0}Max50Text"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CustomerKey"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="PersonalID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max16Text"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardKey"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SurrogateID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DeviceKey"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SurrogateID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text"/&gt;
 *                   &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="SequenceNbr" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Digit"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AccountKey"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AccountID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CardData"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ApplicationID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max19Text"/&gt;
 *                   &lt;element name="LoyaltyInd" type="{http://www.equens.com/cards/issuing/types/v1.0}Max1Text" minOccurs="0"/&gt;
 *                   &lt;element name="LoyaltyNumber" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PaymentData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="StatementReferenceNumber" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AdditionalData" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="AccountInternalID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max13Text" minOccurs="0"/&gt;
 *                   &lt;element name="ProcessingRelationship" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="COID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
 *                             &lt;element name="Owner1" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
 *                             &lt;element name="Owner2" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
 *                             &lt;element name="Owner3" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="PlasticType" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
 *                   &lt;element name="CardStatus" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CardStatusCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
 *                             &lt;element name="CardStatusReasonCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="AccountStatus" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="AccountStatusCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
 *                             &lt;element name="AccountStatusReasonCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IssuePrimaryCardResponseType", propOrder = {
    "cardOrderManagementResponseHeader",
    "productKey",
    "customerKey",
    "cardKey",
    "deviceKey",
    "accountKey",
    "cardData",
    "paymentData",
    "additionalData"
})
public class IssuePrimaryCardResponseType implements ToString2
{

    @XmlElement(name = "CardOrderManagementResponseHeader", required = true)
    protected CardOrderManagementResponseHeader cardOrderManagementResponseHeader;
    @XmlElement(name = "ProductKey", required = true)
    protected IssuePrimaryCardResponseType.ProductKey productKey;
    @XmlElement(name = "CustomerKey", required = true)
    protected IssuePrimaryCardResponseType.CustomerKey customerKey;
    @XmlElement(name = "CardKey", required = true)
    protected IssuePrimaryCardResponseType.CardKey cardKey;
    @XmlElement(name = "DeviceKey", required = true)
    protected IssuePrimaryCardResponseType.DeviceKey deviceKey;
    @XmlElement(name = "AccountKey", required = true)
    protected IssuePrimaryCardResponseType.AccountKey accountKey;
    @XmlElement(name = "CardData", required = true)
    protected IssuePrimaryCardResponseType.CardData cardData;
    @XmlElement(name = "PaymentData")
    protected IssuePrimaryCardResponseType.PaymentData paymentData;
    @XmlElement(name = "AdditionalData")
    protected IssuePrimaryCardResponseType.AdditionalData additionalData;

    /**
     * Gets the value of the cardOrderManagementResponseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link CardOrderManagementResponseHeader }
     *     
     */
    public CardOrderManagementResponseHeader getCardOrderManagementResponseHeader() {
        return cardOrderManagementResponseHeader;
    }

    /**
     * Sets the value of the cardOrderManagementResponseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardOrderManagementResponseHeader }
     *     
     */
    public void setCardOrderManagementResponseHeader(CardOrderManagementResponseHeader value) {
        this.cardOrderManagementResponseHeader = value;
    }

    /**
     * Gets the value of the productKey property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.ProductKey }
     *     
     */
    public IssuePrimaryCardResponseType.ProductKey getProductKey() {
        return productKey;
    }

    /**
     * Sets the value of the productKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.ProductKey }
     *     
     */
    public void setProductKey(IssuePrimaryCardResponseType.ProductKey value) {
        this.productKey = value;
    }

    /**
     * Gets the value of the customerKey property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.CustomerKey }
     *     
     */
    public IssuePrimaryCardResponseType.CustomerKey getCustomerKey() {
        return customerKey;
    }

    /**
     * Sets the value of the customerKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.CustomerKey }
     *     
     */
    public void setCustomerKey(IssuePrimaryCardResponseType.CustomerKey value) {
        this.customerKey = value;
    }

    /**
     * Gets the value of the cardKey property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.CardKey }
     *     
     */
    public IssuePrimaryCardResponseType.CardKey getCardKey() {
        return cardKey;
    }

    /**
     * Sets the value of the cardKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.CardKey }
     *     
     */
    public void setCardKey(IssuePrimaryCardResponseType.CardKey value) {
        this.cardKey = value;
    }

    /**
     * Gets the value of the deviceKey property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.DeviceKey }
     *     
     */
    public IssuePrimaryCardResponseType.DeviceKey getDeviceKey() {
        return deviceKey;
    }

    /**
     * Sets the value of the deviceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.DeviceKey }
     *     
     */
    public void setDeviceKey(IssuePrimaryCardResponseType.DeviceKey value) {
        this.deviceKey = value;
    }

    /**
     * Gets the value of the accountKey property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.AccountKey }
     *     
     */
    public IssuePrimaryCardResponseType.AccountKey getAccountKey() {
        return accountKey;
    }

    /**
     * Sets the value of the accountKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.AccountKey }
     *     
     */
    public void setAccountKey(IssuePrimaryCardResponseType.AccountKey value) {
        this.accountKey = value;
    }

    /**
     * Gets the value of the cardData property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.CardData }
     *     
     */
    public IssuePrimaryCardResponseType.CardData getCardData() {
        return cardData;
    }

    /**
     * Sets the value of the cardData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.CardData }
     *     
     */
    public void setCardData(IssuePrimaryCardResponseType.CardData value) {
        this.cardData = value;
    }

    /**
     * Gets the value of the paymentData property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.PaymentData }
     *     
     */
    public IssuePrimaryCardResponseType.PaymentData getPaymentData() {
        return paymentData;
    }

    /**
     * Sets the value of the paymentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.PaymentData }
     *     
     */
    public void setPaymentData(IssuePrimaryCardResponseType.PaymentData value) {
        this.paymentData = value;
    }

    /**
     * Gets the value of the additionalData property.
     * 
     * @return
     *     possible object is
     *     {@link IssuePrimaryCardResponseType.AdditionalData }
     *     
     */
    public IssuePrimaryCardResponseType.AdditionalData getAdditionalData() {
        return additionalData;
    }

    /**
     * Sets the value of the additionalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuePrimaryCardResponseType.AdditionalData }
     *     
     */
    public void setAdditionalData(IssuePrimaryCardResponseType.AdditionalData value) {
        this.additionalData = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            CardOrderManagementResponseHeader theCardOrderManagementResponseHeader;
            theCardOrderManagementResponseHeader = this.getCardOrderManagementResponseHeader();
            strategy.appendField(locator, this, "cardOrderManagementResponseHeader", buffer, theCardOrderManagementResponseHeader, (this.cardOrderManagementResponseHeader!= null));
        }
        {
            IssuePrimaryCardResponseType.ProductKey theProductKey;
            theProductKey = this.getProductKey();
            strategy.appendField(locator, this, "productKey", buffer, theProductKey, (this.productKey!= null));
        }
        {
            IssuePrimaryCardResponseType.CustomerKey theCustomerKey;
            theCustomerKey = this.getCustomerKey();
            strategy.appendField(locator, this, "customerKey", buffer, theCustomerKey, (this.customerKey!= null));
        }
        {
            IssuePrimaryCardResponseType.CardKey theCardKey;
            theCardKey = this.getCardKey();
            strategy.appendField(locator, this, "cardKey", buffer, theCardKey, (this.cardKey!= null));
        }
        {
            IssuePrimaryCardResponseType.DeviceKey theDeviceKey;
            theDeviceKey = this.getDeviceKey();
            strategy.appendField(locator, this, "deviceKey", buffer, theDeviceKey, (this.deviceKey!= null));
        }
        {
            IssuePrimaryCardResponseType.AccountKey theAccountKey;
            theAccountKey = this.getAccountKey();
            strategy.appendField(locator, this, "accountKey", buffer, theAccountKey, (this.accountKey!= null));
        }
        {
            IssuePrimaryCardResponseType.CardData theCardData;
            theCardData = this.getCardData();
            strategy.appendField(locator, this, "cardData", buffer, theCardData, (this.cardData!= null));
        }
        {
            IssuePrimaryCardResponseType.PaymentData thePaymentData;
            thePaymentData = this.getPaymentData();
            strategy.appendField(locator, this, "paymentData", buffer, thePaymentData, (this.paymentData!= null));
        }
        {
            IssuePrimaryCardResponseType.AdditionalData theAdditionalData;
            theAdditionalData = this.getAdditionalData();
            strategy.appendField(locator, this, "additionalData", buffer, theAdditionalData, (this.additionalData!= null));
        }
        return buffer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AccountID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountID"
    })
    public static class AccountKey implements ToString2
    {

        @XmlElement(name = "AccountID", required = true)
        protected String accountID;

        /**
         * Gets the value of the accountID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountID() {
            return accountID;
        }

        /**
         * Sets the value of the accountID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountID(String value) {
            this.accountID = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theAccountID;
                theAccountID = this.getAccountID();
                strategy.appendField(locator, this, "accountID", buffer, theAccountID, (this.accountID!= null));
            }
            return buffer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="AccountInternalID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max13Text" minOccurs="0"/&gt;
     *         &lt;element name="ProcessingRelationship" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="COID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
     *                   &lt;element name="Owner1" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
     *                   &lt;element name="Owner2" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
     *                   &lt;element name="Owner3" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="PlasticType" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
     *         &lt;element name="CardStatus" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="CardStatusCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
     *                   &lt;element name="CardStatusReasonCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="AccountStatus" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="AccountStatusCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
     *                   &lt;element name="AccountStatusReasonCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountInternalID",
        "processingRelationship",
        "plasticType",
        "cardStatus",
        "accountStatus"
    })
    public static class AdditionalData implements ToString2
    {

        @XmlElement(name = "AccountInternalID")
        protected String accountInternalID;
        @XmlElement(name = "ProcessingRelationship")
        protected IssuePrimaryCardResponseType.AdditionalData.ProcessingRelationship processingRelationship;
        @XmlElement(name = "PlasticType")
        protected String plasticType;
        @XmlElement(name = "CardStatus")
        protected IssuePrimaryCardResponseType.AdditionalData.CardStatus cardStatus;
        @XmlElement(name = "AccountStatus")
        protected IssuePrimaryCardResponseType.AdditionalData.AccountStatus accountStatus;

        /**
         * Gets the value of the accountInternalID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountInternalID() {
            return accountInternalID;
        }

        /**
         * Sets the value of the accountInternalID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountInternalID(String value) {
            this.accountInternalID = value;
        }

        /**
         * Gets the value of the processingRelationship property.
         * 
         * @return
         *     possible object is
         *     {@link IssuePrimaryCardResponseType.AdditionalData.ProcessingRelationship }
         *     
         */
        public IssuePrimaryCardResponseType.AdditionalData.ProcessingRelationship getProcessingRelationship() {
            return processingRelationship;
        }

        /**
         * Sets the value of the processingRelationship property.
         * 
         * @param value
         *     allowed object is
         *     {@link IssuePrimaryCardResponseType.AdditionalData.ProcessingRelationship }
         *     
         */
        public void setProcessingRelationship(IssuePrimaryCardResponseType.AdditionalData.ProcessingRelationship value) {
            this.processingRelationship = value;
        }

        /**
         * Gets the value of the plasticType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlasticType() {
            return plasticType;
        }

        /**
         * Sets the value of the plasticType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlasticType(String value) {
            this.plasticType = value;
        }

        /**
         * Gets the value of the cardStatus property.
         * 
         * @return
         *     possible object is
         *     {@link IssuePrimaryCardResponseType.AdditionalData.CardStatus }
         *     
         */
        public IssuePrimaryCardResponseType.AdditionalData.CardStatus getCardStatus() {
            return cardStatus;
        }

        /**
         * Sets the value of the cardStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link IssuePrimaryCardResponseType.AdditionalData.CardStatus }
         *     
         */
        public void setCardStatus(IssuePrimaryCardResponseType.AdditionalData.CardStatus value) {
            this.cardStatus = value;
        }

        /**
         * Gets the value of the accountStatus property.
         * 
         * @return
         *     possible object is
         *     {@link IssuePrimaryCardResponseType.AdditionalData.AccountStatus }
         *     
         */
        public IssuePrimaryCardResponseType.AdditionalData.AccountStatus getAccountStatus() {
            return accountStatus;
        }

        /**
         * Sets the value of the accountStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link IssuePrimaryCardResponseType.AdditionalData.AccountStatus }
         *     
         */
        public void setAccountStatus(IssuePrimaryCardResponseType.AdditionalData.AccountStatus value) {
            this.accountStatus = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theAccountInternalID;
                theAccountInternalID = this.getAccountInternalID();
                strategy.appendField(locator, this, "accountInternalID", buffer, theAccountInternalID, (this.accountInternalID!= null));
            }
            {
                IssuePrimaryCardResponseType.AdditionalData.ProcessingRelationship theProcessingRelationship;
                theProcessingRelationship = this.getProcessingRelationship();
                strategy.appendField(locator, this, "processingRelationship", buffer, theProcessingRelationship, (this.processingRelationship!= null));
            }
            {
                String thePlasticType;
                thePlasticType = this.getPlasticType();
                strategy.appendField(locator, this, "plasticType", buffer, thePlasticType, (this.plasticType!= null));
            }
            {
                IssuePrimaryCardResponseType.AdditionalData.CardStatus theCardStatus;
                theCardStatus = this.getCardStatus();
                strategy.appendField(locator, this, "cardStatus", buffer, theCardStatus, (this.cardStatus!= null));
            }
            {
                IssuePrimaryCardResponseType.AdditionalData.AccountStatus theAccountStatus;
                theAccountStatus = this.getAccountStatus();
                strategy.appendField(locator, this, "accountStatus", buffer, theAccountStatus, (this.accountStatus!= null));
            }
            return buffer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="AccountStatusCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
         *         &lt;element name="AccountStatusReasonCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "accountStatusCode",
            "accountStatusReasonCode"
        })
        public static class AccountStatus implements ToString2
        {

            @XmlElement(name = "AccountStatusCode")
            protected String accountStatusCode;
            @XmlElement(name = "AccountStatusReasonCode")
            protected String accountStatusReasonCode;

            /**
             * Gets the value of the accountStatusCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccountStatusCode() {
                return accountStatusCode;
            }

            /**
             * Sets the value of the accountStatusCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccountStatusCode(String value) {
                this.accountStatusCode = value;
            }

            /**
             * Gets the value of the accountStatusReasonCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccountStatusReasonCode() {
                return accountStatusReasonCode;
            }

            /**
             * Sets the value of the accountStatusReasonCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccountStatusReasonCode(String value) {
                this.accountStatusReasonCode = value;
            }

            public String toString() {
                final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
                final StringBuilder buffer = new StringBuilder();
                append(null, buffer, strategy);
                return buffer.toString();
            }

            public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
                strategy.appendStart(locator, this, buffer);
                appendFields(locator, buffer, strategy);
                strategy.appendEnd(locator, this, buffer);
                return buffer;
            }

            public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
                {
                    String theAccountStatusCode;
                    theAccountStatusCode = this.getAccountStatusCode();
                    strategy.appendField(locator, this, "accountStatusCode", buffer, theAccountStatusCode, (this.accountStatusCode!= null));
                }
                {
                    String theAccountStatusReasonCode;
                    theAccountStatusReasonCode = this.getAccountStatusReasonCode();
                    strategy.appendField(locator, this, "accountStatusReasonCode", buffer, theAccountStatusReasonCode, (this.accountStatusReasonCode!= null));
                }
                return buffer;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="CardStatusCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
         *         &lt;element name="CardStatusReasonCode" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Text" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cardStatusCode",
            "cardStatusReasonCode"
        })
        public static class CardStatus implements ToString2
        {

            @XmlElement(name = "CardStatusCode")
            protected String cardStatusCode;
            @XmlElement(name = "CardStatusReasonCode")
            protected String cardStatusReasonCode;

            /**
             * Gets the value of the cardStatusCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCardStatusCode() {
                return cardStatusCode;
            }

            /**
             * Sets the value of the cardStatusCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCardStatusCode(String value) {
                this.cardStatusCode = value;
            }

            /**
             * Gets the value of the cardStatusReasonCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCardStatusReasonCode() {
                return cardStatusReasonCode;
            }

            /**
             * Sets the value of the cardStatusReasonCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCardStatusReasonCode(String value) {
                this.cardStatusReasonCode = value;
            }

            public String toString() {
                final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
                final StringBuilder buffer = new StringBuilder();
                append(null, buffer, strategy);
                return buffer.toString();
            }

            public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
                strategy.appendStart(locator, this, buffer);
                appendFields(locator, buffer, strategy);
                strategy.appendEnd(locator, this, buffer);
                return buffer;
            }

            public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
                {
                    String theCardStatusCode;
                    theCardStatusCode = this.getCardStatusCode();
                    strategy.appendField(locator, this, "cardStatusCode", buffer, theCardStatusCode, (this.cardStatusCode!= null));
                }
                {
                    String theCardStatusReasonCode;
                    theCardStatusReasonCode = this.getCardStatusReasonCode();
                    strategy.appendField(locator, this, "cardStatusReasonCode", buffer, theCardStatusReasonCode, (this.cardStatusReasonCode!= null));
                }
                return buffer;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="COID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
         *         &lt;element name="Owner1" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
         *         &lt;element name="Owner2" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
         *         &lt;element name="Owner3" type="{http://www.equens.com/cards/issuing/types/v1.0}Max5Text" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "coid",
            "owner1",
            "owner2",
            "owner3"
        })
        public static class ProcessingRelationship implements ToString2
        {

            @XmlElement(name = "COID")
            protected String coid;
            @XmlElement(name = "Owner1")
            protected String owner1;
            @XmlElement(name = "Owner2")
            protected String owner2;
            @XmlElement(name = "Owner3")
            protected String owner3;

            /**
             * Gets the value of the coid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCOID() {
                return coid;
            }

            /**
             * Sets the value of the coid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCOID(String value) {
                this.coid = value;
            }

            /**
             * Gets the value of the owner1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwner1() {
                return owner1;
            }

            /**
             * Sets the value of the owner1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwner1(String value) {
                this.owner1 = value;
            }

            /**
             * Gets the value of the owner2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwner2() {
                return owner2;
            }

            /**
             * Sets the value of the owner2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwner2(String value) {
                this.owner2 = value;
            }

            /**
             * Gets the value of the owner3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOwner3() {
                return owner3;
            }

            /**
             * Sets the value of the owner3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOwner3(String value) {
                this.owner3 = value;
            }

            public String toString() {
                final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
                final StringBuilder buffer = new StringBuilder();
                append(null, buffer, strategy);
                return buffer.toString();
            }

            public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
                strategy.appendStart(locator, this, buffer);
                appendFields(locator, buffer, strategy);
                strategy.appendEnd(locator, this, buffer);
                return buffer;
            }

            public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
                {
                    String theCOID;
                    theCOID = this.getCOID();
                    strategy.appendField(locator, this, "coid", buffer, theCOID, (this.coid!= null));
                }
                {
                    String theOwner1;
                    theOwner1 = this.getOwner1();
                    strategy.appendField(locator, this, "owner1", buffer, theOwner1, (this.owner1 != null));
                }
                {
                    String theOwner2;
                    theOwner2 = this.getOwner2();
                    strategy.appendField(locator, this, "owner2", buffer, theOwner2, (this.owner2 != null));
                }
                {
                    String theOwner3;
                    theOwner3 = this.getOwner3();
                    strategy.appendField(locator, this, "owner3", buffer, theOwner3, (this.owner3 != null));
                }
                return buffer;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ApplicationID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max19Text"/&gt;
     *         &lt;element name="LoyaltyInd" type="{http://www.equens.com/cards/issuing/types/v1.0}Max1Text" minOccurs="0"/&gt;
     *         &lt;element name="LoyaltyNumber" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicationID",
        "loyaltyInd",
        "loyaltyNumber"
    })
    public static class CardData implements ToString2
    {

        @XmlElement(name = "ApplicationID", required = true)
        protected String applicationID;
        @XmlElement(name = "LoyaltyInd")
        protected String loyaltyInd;
        @XmlElement(name = "LoyaltyNumber")
        protected String loyaltyNumber;

        /**
         * Gets the value of the applicationID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplicationID() {
            return applicationID;
        }

        /**
         * Sets the value of the applicationID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplicationID(String value) {
            this.applicationID = value;
        }

        /**
         * Gets the value of the loyaltyInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLoyaltyInd() {
            return loyaltyInd;
        }

        /**
         * Sets the value of the loyaltyInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLoyaltyInd(String value) {
            this.loyaltyInd = value;
        }

        /**
         * Gets the value of the loyaltyNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLoyaltyNumber() {
            return loyaltyNumber;
        }

        /**
         * Sets the value of the loyaltyNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLoyaltyNumber(String value) {
            this.loyaltyNumber = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theApplicationID;
                theApplicationID = this.getApplicationID();
                strategy.appendField(locator, this, "applicationID", buffer, theApplicationID, (this.applicationID!= null));
            }
            {
                String theLoyaltyInd;
                theLoyaltyInd = this.getLoyaltyInd();
                strategy.appendField(locator, this, "loyaltyInd", buffer, theLoyaltyInd, (this.loyaltyInd!= null));
            }
            {
                String theLoyaltyNumber;
                theLoyaltyNumber = this.getLoyaltyNumber();
                strategy.appendField(locator, this, "loyaltyNumber", buffer, theLoyaltyNumber, (this.loyaltyNumber!= null));
            }
            return buffer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SurrogateID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "surrogateID"
    })
    public static class CardKey implements ToString2
    {

        @XmlElement(name = "SurrogateID", required = true)
        protected String surrogateID;

        /**
         * Gets the value of the surrogateID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSurrogateID() {
            return surrogateID;
        }

        /**
         * Sets the value of the surrogateID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSurrogateID(String value) {
            this.surrogateID = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theSurrogateID;
                theSurrogateID = this.getSurrogateID();
                strategy.appendField(locator, this, "surrogateID", buffer, theSurrogateID, (this.surrogateID!= null));
            }
            return buffer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="PersonalID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max16Text"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "personalID"
    })
    public static class CustomerKey implements ToString2
    {

        @XmlElement(name = "PersonalID", required = true)
        protected String personalID;

        /**
         * Gets the value of the personalID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonalID() {
            return personalID;
        }

        /**
         * Sets the value of the personalID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonalID(String value) {
            this.personalID = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String thePersonalID;
                thePersonalID = this.getPersonalID();
                strategy.appendField(locator, this, "personalID", buffer, thePersonalID, (this.personalID!= null));
            }
            return buffer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SurrogateID" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text"/&gt;
     *         &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="SequenceNbr" type="{http://www.equens.com/cards/issuing/types/v1.0}Max3Digit"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "surrogateID",
        "expiryDate",
        "sequenceNbr"
    })
    public static class DeviceKey implements ToString2
    {

        @XmlElement(name = "SurrogateID", required = true)
        protected String surrogateID;
        @XmlElement(name = "ExpiryDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar expiryDate;
        @XmlElement(name = "SequenceNbr", required = true)
        protected BigInteger sequenceNbr;

        /**
         * Gets the value of the surrogateID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSurrogateID() {
            return surrogateID;
        }

        /**
         * Sets the value of the surrogateID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSurrogateID(String value) {
            this.surrogateID = value;
        }

        /**
         * Gets the value of the expiryDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getExpiryDate() {
            return expiryDate;
        }

        /**
         * Sets the value of the expiryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setExpiryDate(XMLGregorianCalendar value) {
            this.expiryDate = value;
        }

        /**
         * Gets the value of the sequenceNbr property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSequenceNbr() {
            return sequenceNbr;
        }

        /**
         * Sets the value of the sequenceNbr property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSequenceNbr(BigInteger value) {
            this.sequenceNbr = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theSurrogateID;
                theSurrogateID = this.getSurrogateID();
                strategy.appendField(locator, this, "surrogateID", buffer, theSurrogateID, (this.surrogateID!= null));
            }
            {
                XMLGregorianCalendar theExpiryDate;
                theExpiryDate = this.getExpiryDate();
                strategy.appendField(locator, this, "expiryDate", buffer, theExpiryDate, (this.expiryDate!= null));
            }
            {
                BigInteger theSequenceNbr;
                theSequenceNbr = this.getSequenceNbr();
                strategy.appendField(locator, this, "sequenceNbr", buffer, theSequenceNbr, (this.sequenceNbr!= null));
            }
            return buffer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="StatementReferenceNumber" type="{http://www.equens.com/cards/issuing/types/v1.0}Max23Text" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "statementReferenceNumber"
    })
    public static class PaymentData implements ToString2
    {

        @XmlElement(name = "StatementReferenceNumber")
        protected String statementReferenceNumber;

        /**
         * Gets the value of the statementReferenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatementReferenceNumber() {
            return statementReferenceNumber;
        }

        /**
         * Sets the value of the statementReferenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatementReferenceNumber(String value) {
            this.statementReferenceNumber = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theStatementReferenceNumber;
                theStatementReferenceNumber = this.getStatementReferenceNumber();
                strategy.appendField(locator, this, "statementReferenceNumber", buffer, theStatementReferenceNumber, (this.statementReferenceNumber!= null));
            }
            return buffer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="IssuerKeyType" type="{http://www.equens.com/cards/issuing/types/v1.0}Max6Text"/&gt;
     *         &lt;element name="ProductKey" type="{http://www.equens.com/cards/issuing/types/v1.0}Max50Text"/&gt;
     *         &lt;element name="IssuerKey" type="{http://www.equens.com/cards/issuing/types/v1.0}Max50Text"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "issuerKeyType",
        "productKey",
        "issuerKey"
    })
    public static class ProductKey implements ToString2
    {

        @XmlElement(name = "IssuerKeyType", required = true)
        protected String issuerKeyType;
        @XmlElement(name = "ProductKey", required = true)
        protected String productKey;
        @XmlElement(name = "IssuerKey", required = true)
        protected String issuerKey;

        /**
         * Gets the value of the issuerKeyType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssuerKeyType() {
            return issuerKeyType;
        }

        /**
         * Sets the value of the issuerKeyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssuerKeyType(String value) {
            this.issuerKeyType = value;
        }

        /**
         * Gets the value of the productKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductKey() {
            return productKey;
        }

        /**
         * Sets the value of the productKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductKey(String value) {
            this.productKey = value;
        }

        /**
         * Gets the value of the issuerKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssuerKey() {
            return issuerKey;
        }

        /**
         * Sets the value of the issuerKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssuerKey(String value) {
            this.issuerKey = value;
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                String theIssuerKeyType;
                theIssuerKeyType = this.getIssuerKeyType();
                strategy.appendField(locator, this, "issuerKeyType", buffer, theIssuerKeyType, (this.issuerKeyType!= null));
            }
            {
                String theProductKey;
                theProductKey = this.getProductKey();
                strategy.appendField(locator, this, "productKey", buffer, theProductKey, (this.productKey!= null));
            }
            {
                String theIssuerKey;
                theIssuerKey = this.getIssuerKey();
                strategy.appendField(locator, this, "issuerKey", buffer, theIssuerKey, (this.issuerKey!= null));
            }
            return buffer;
        }

    }

}
