//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 04:16:53 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.equens.com/cards/issuing/messages/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package db.pcci.ita.msa.cards.soap.client;
